[package]
name = "colors"
author = "pgattic"
version = "0.1.0"

[build.code]
command = ["wat2wasm", "src/main.wat", "-o", "src/main.wasm"]
output = "src/main.wasm"

[build.assets]
dir = "assets"
sprite_tiles = "spr.4bpp"
background_tiles = "bg.4bpp"
background_map = "bg.map"
